// Five-rung pedagogical ladder for the redesigned Intro page.
// Each rung is a paramOverrides object layered on top of UI_CONFIG from
// src/presets.js. See INTRO_LADDER_MAPPING.md for rationale.
//
// `greekCollapse: true` activates the pedagogical post-processing overlay
// in src/pages/IntroPage.jsx (GE-penalty above 150 % PIB for étape 1 +
// debt-restructuring event at 3× PIB for étape 1, 5× PIB for the others
// — which they never reach under their reform params, so it's a no-op
// there).

export const LADDER_RUNGS = [
  {
    id: 'actuel',
    num: 1,
    label: 'Système actuel',
    short: 'Actuel',
    headline: 'Aujourd\u2019hui : un système par répartition sous perfusion',
    summary: "Avec la démographie actuelle, notre système par répartition suppose des transferts permanents du budget général (donc des autres taxes — CSG, FSV, TVA \u2248 40 Md€/an) pour boucler ses fins de mois, et cela ne suffit même pas car le budget de l'État est déficitaire pour cette raison. Sans réforme, la dépendance s'aggrave avec le vieillissement, et la dette avec, jusqu'à ce que nous nous retrouvions dans la même situation que les Grecs. Pour rappel, ils ont dû couper les dépenses de l'État à l'os. Avec les paramètres budgétaires de la France, seules de grosses coupes des retraites pourraient suffire.",
    closestPreset: 'derived (counterfactual + transferts BG actuels)',
    color: '#b85c3c',
    greekCollapse: true,
    paramOverrides: {
      useEquinoxe: false,
      enableCapi: false,
      hlmDiscount: false,
      delta: 0,
      rho: 0,
      lambda: 0,
      employmentRateTarget: 0.69,
      chileMode: false,
      swedenMode: false,
      fiscalTransferMode: 'full',
      demoProfile: 'realistic',
    },
  },
  {
    id: 'equinoxe',
    num: 2,
    label: 'Rééquilibrage Équinoxe',
    short: 'Équinoxe',
    headline: 'On rééquilibre : moins de pression sur le budget général',
    summary: "Le rééquilibrage proposé par Équinoxe réduit progressivement les pensions élevées, supprime l'abattement de 10 %, et restaure la CSG/CRDS à taux plein, sans toucher aux petites retraites. Ce rééquilibrage suffit pour que la France reste solvable, mais les retraites restent structurellement dépendantes des transferts du budget général.",
    closestPreset: 'equinoxeOnly',
    color: '#c9a961',
    greekCollapse: true,
    paramOverrides: {
      useEquinoxe: true,
      equinoxePhasing: 'phased-10y',
      enableCapi: false,
      hlmDiscount: false,
      delta: 0,
      rho: 0,
      lambda: 0,
      employmentRateTarget: 0.69,
      chileMode: false,
      swedenMode: false,
      fiscalTransferMode: 'full',
      demoProfile: 'realistic',
    },
  },
  {
    id: 'suede',
    num: 3,
    label: 'Mode Suédois',
    short: 'Suède',
    headline: 'Suède : équilibrage automatique + petit pilier capi',
    summary: "Cette proposition de réforme est inspirée du système suédois Inkomstpension (pension par revenu) + Premiepension (pension de prime), dernières « grandes réformes » dans un pays européen (1999). Dans ce modèle, nous restons dans un système par répartition, mais avec un compte notionnel par cotisant, complété par un petit pilier de capitalisation (contribution de 4 % des salaires, que les individus peuvent supplémenter). Le mécanisme d'équilibrage automatique (ABM) coupe l'indexation des pensions lorsque les ressources du système passent en-dessous des décaissements, gardant le système solvable sans recourir à la dette. Cette solution élimine le conflit intergénérationnel parce que les retraités et les actifs partagent les fruits de la croissance économique.",
    closestPreset: 'v1_default + swedenMode (canonical toggle)',
    color: '#0d9488',
    greekCollapse: true,
    paramOverrides: {
      useEquinoxe: true,
      equinoxePhasing: 'phased-10y',
      enableCapi: false,
      swedenMode: true,
      swedenABM: true,
      swedenCapiRate: 0.04,
      chileMode: false,
      hlmDiscount: false,
      delta: 0,
      rho: 0,
      lambda: 0,
      employmentRateTarget: 0.69,
      fiscalTransferMode: 'none',
      demoProfile: 'realistic',
    },
  },
  {
    id: 'chili',
    num: 4,
    label: 'Mode Chilien',
    short: 'Chili',
    headline: 'Chili : capitalisation totale + obligations de reconnaissance',
    summary: "Notre deuxième alternative est de suivre le modèle chilien. Ici, les cotisations basculent intégralement vers la capitalisation. Les droits acquis sont convertis en obligations indexées sur l'inflation, qui se remboursent à mesure que chaque cotisant prend sa retraite. La dette de transition est explicite et lisible — mais elle est massive si on ne la finance pas.",
    closestPreset: 'v1_default + chileMode (canonical toggle)',
    color: '#7c3aed',
    greekCollapse: true,
    paramOverrides: {
      useEquinoxe: true,
      equinoxePhasing: 'phased-10y',
      enableCapi: true,
      chileMode: true,
      swedenMode: false,
      cutoffAge: 50,
      hlmDiscount: true,
      delta: 0.3,
      rho: 0.05,
      T_hlm: 20,
      lambda: 0,
      tauK: 0,
      thetaBuffer: 0.01,
      employmentRateTarget: 0.69,
      fiscalTransferMode: 'none',
      demoProfile: 'realistic',
    },
  },
  {
    id: 'chili_finance',
    num: 5,
    label: 'Chili + transition financée',
    short: 'Chili financé',
    headline: 'Chili financé : on maintient les transferts (comme aujourd\u2019hui, mais sans dette)',
    summary: "Même bascule que le Mode Chilien, mais le solde négatif de la transition est couvert par les transferts du budget général déjà existants (CSG, FSV, TVA) — sans recourir à une dette nouvelle. À mesure que le pilier de capitalisation devient autonome, ces transferts s'éteignent progressivement.",
    closestPreset: 'v1_default + chileMode + fiscalTransferMode:no-debt',
    color: '#1e293b',
    greekCollapse: true,
    paramOverrides: {
      useEquinoxe: true,
      equinoxePhasing: 'phased-10y',
      enableCapi: true,
      chileMode: true,
      swedenMode: false,
      cutoffAge: 50,
      hlmDiscount: true,
      delta: 0.3,
      rho: 0.05,
      T_hlm: 20,
      lambda: 0.30,
      tauK: 0.025,
      thetaBuffer: 0.01,
      employmentRateTarget: 0.759,
      employmentTransitionYears: 8,
      fiscalTransferMode: 'no-debt',
      demoProfile: 'realistic',
    },
  },
];
